<?php

namespace Database\Seeders;

use App\Models\Investment;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Http;

class InvestmentSeeder extends Seeder
{
    // ── Cloudinary helpers (same approach as the controller) ──────────────────

    private function cloudinaryCredentials(): array
    {
        $url    = config('filesystems.disks.cloudinary.url');
        $parsed = parse_url($url);
        return [
            'cloud_name' => $parsed['host'],
            'api_key'    => $parsed['user'],
            'api_secret' => urldecode($parsed['pass']),
        ];
    }

    private function cloudinarySign(array $params, string $apiSecret): string
    {
        ksort($params);
        $parts = [];
        foreach ($params as $key => $value) {
            $parts[] = $key . '=' . $value;
        }
        return sha1(implode('&', $parts) . $apiSecret);
    }

    /** Upload a remote image URL directly to Cloudinary and return the secure_url */
    private function uploadUrl(string $remoteUrl, string $folder): string
    {
        $creds      = $this->cloudinaryCredentials();
        $timestamp  = time();
        $signParams = ['folder' => $folder, 'timestamp' => $timestamp];
        $signature  = $this->cloudinarySign($signParams, $creds['api_secret']);

        $response = Http::timeout(60)->post(
            "https://api.cloudinary.com/v1_1/{$creds['cloud_name']}/image/upload",
            [
                'file'      => $remoteUrl,
                'api_key'   => $creds['api_key'],
                'timestamp' => $timestamp,
                'folder'    => $folder,
                'signature' => $signature,
            ]
        );

        if (!$response->successful()) {
            $this->command->warn("Upload failed for {$remoteUrl}: " . $response->body());
            return $remoteUrl; // fall back to original URL so the record still saves
        }

        return $response->json('secure_url');
    }

    // ── Seed data ─────────────────────────────────────────────────────────────

    public function run(): void
    {
        // Each entry: [main_image_url, [gallery_url, ...]]
        // Using Unsplash property photos (free, no auth needed)
        $investments = [
            // ── 1. Downtown Dubai Luxury Apartment ─────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Burj Vista Luxury Residences',
                'location'       => 'Downtown Dubai, Burj Khalifa District',
                'historic_yield' => 8.5,
                'total_assets'   => 8500000,
                'min_investment' => 85000,
                'share_price'    => 850,
                'investors'      => 100,
                'size'           => 1200,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'A stunning 2-bedroom apartment in the iconic Burj Vista tower offering unobstructed views of the Burj Khalifa and Dubai Fountain. Finished to the highest specification with marble floors, floor-to-ceiling windows, and a fully equipped smart-home system. Managed by a leading hospitality brand achieving 92% occupancy year-round.',
                'amenities'      => ['Swimming Pool', 'Gym', '24/7 Security', 'Concierge', 'Valet Parking', 'Smart Home', 'High-Speed Internet'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 2. Palm Jumeirah Signature Villa ───────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Villa',
                'name'           => 'Palm Jumeirah Signature Villa',
                'location'       => 'Palm Jumeirah, Dubai',
                'historic_yield' => 7.2,
                'total_assets'   => 18000000,
                'min_investment' => 180000,
                'share_price'    => 1800,
                'investors'      => 100,
                'size'           => 8500,
                'bedrooms'       => 5,
                'bathrooms'      => 6,
                'parking'        => 4,
                'year_built'     => 2019,
                'description'    => 'An extraordinary beachfront villa on the exclusive Palm Jumeirah frond, offering direct private beach access and uninterrupted views of the Arabian Gulf and Dubai skyline. Spanning five en-suite bedrooms, a dedicated cinema room, full smart-home automation, and a temperature-controlled infinity pool. Premium rental returns driven by constant demand from high-net-worth visitors.',
                'amenities'      => ['Private Beach', 'Infinity Pool', 'Private Gym', 'Smart Home', '24/7 Security', 'Parking Lot', 'Elevator'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                ],
            ],
            // ── 3. Dubai Marina Sky Penthouse ──────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Penthouse',
                'name'           => 'Dubai Marina Sky Penthouse',
                'location'       => 'Dubai Marina, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 12500000,
                'size'           => 5800,
                'bedrooms'       => 4,
                'bathrooms'      => 4,
                'parking'        => 3,
                'year_built'     => 2021,
                'description'    => 'A full-floor sky penthouse occupying the top level of a prestigious Dubai Marina tower, boasting 270° panoramic views stretching from Palm Jumeirah to the JBR Walk. Featuring a private rooftop terrace with a plunge pool, handcrafted Italian kitchen, and bespoke interior design by a globally recognised firm. The ultimate statement of luxury living in new Dubai.',
                'amenities'      => ['Rooftop Plunge Pool', 'Private Terrace', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Gym', 'Elevator'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 4. DIFC Boulevard Residences ───────────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Serviced Apartment',
                'name'           => 'DIFC Boulevard Residences',
                'location'       => 'Dubai International Financial Centre (DIFC)',
                'historic_yield' => 9.1,
                'total_assets'   => 22000000,
                'min_investment' => 110000,
                'share_price'    => 1100,
                'investors'      => 200,
                'size'           => 950,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2020,
                'description'    => 'Professionally managed serviced apartments in the heart of DIFC, Dubai\'s premier financial and arts district. Delivered fully furnished and white-glove serviced, catering to C-suite executives and long-stay corporate guests. Strong USD-denominated lease agreements underpin consistent 9%+ net yields for investors.',
                'amenities'      => ['Gym', 'Concierge', '24/7 Security', 'High-Speed Internet', 'Swimming Pool', 'Smart Home', 'Elevator'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                ],
            ],
            // ── 5. JBR Ocean Heights Hotel Apartment ───────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Hotel Apartment',
                'name'           => 'JBR Ocean Heights',
                'location'       => 'Jumeirah Beach Residence (JBR), Dubai',
                'historic_yield' => 10.0,
                'total_assets'   => 5600000,
                'min_investment' => 56000,
                'share_price'    => 560,
                'investors'      => 100,
                'size'           => 850,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2023,
                'description'    => 'Brand-new branded hotel apartments steps from the world-famous JBR beach strip. Operated under a five-star hospitality management agreement with guaranteed minimum returns to investors. With direct beach access, rooftop dining, and a state-of-the-art wellness centre, occupancy consistently exceeds 88% year-round.',
                'amenities'      => ['Beach Access', 'Swimming Pool', 'Rooftop Restaurant', 'Concierge', 'Smart Home', '24/7 Security', 'Gym'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                ],
            ],
            // ── 6. Emirates Hills Grand Estate ─────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Villa',
                'name'           => 'Emirates Hills Grand Estate',
                'location'       => 'Emirates Hills, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 45000000,
                'size'           => 18000,
                'bedrooms'       => 8,
                'bathrooms'      => 9,
                'parking'        => 8,
                'year_built'     => 2018,
                'description'    => 'A landmark mega-mansion in Emirates Hills — Dubai\'s most prestigious gated enclave — positioned on an oversized golf-course plot with sweeping fairway views. Eight grand en-suite bedrooms, a private cinema, wine cellar, equipped home gym, and a resort-style swimming pool with cabana. Flawlessly crafted by one of the region\'s most awarded architecture studios.',
                'amenities'      => ['Golf Course View', 'Private Pool', 'Private Cinema', 'Wine Cellar', 'Smart Home', 'Private Gym', '24/7 Security', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                ],
            ],
            // ── 7. Business Bay Canal Residences ───────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Business Bay Canal Residences',
                'location'       => 'Business Bay, Dubai',
                'historic_yield' => 8.8,
                'total_assets'   => 6200000,
                'min_investment' => 62000,
                'share_price'    => 620,
                'investors'      => 100,
                'size'           => 900,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'Stylish 2-bedroom apartments overlooking the Dubai Water Canal in the dynamic Business Bay district, minutes from the Burj Khalifa and Dubai Mall. A fully managed short-term rental programme returns robust yields to investors, supported by high demand from business travellers and leisure tourists across the year.',
                'amenities'      => ['Canal View', 'Swimming Pool', 'Gym', '24/7 Security', 'High-Speed Internet', 'Smart Home', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                ],
            ],
            // ── 8. Arabian Ranches III Townhouses ──────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Townhouse',
                'name'           => 'Arabian Ranches III Townhouses',
                'location'       => 'Arabian Ranches III, Dubai',
                'historic_yield' => 7.5,
                'total_assets'   => 3800000,
                'min_investment' => 38000,
                'share_price'    => 380,
                'investors'      => 100,
                'size'           => 2800,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2023,
                'description'    => 'Contemporary 3-bedroom townhouses within Emaar\'s sought-after Arabian Ranches III master community. Set amidst landscaped parks, cycling trails, and a championship polo club. Spacious open-plan layouts with private rear gardens make these ideal long-let family homes, with strong tenant demand from Dubai\'s growing expatriate population.',
                'amenities'      => ['Communal Pool', 'Kids Play Area', 'Cycling Trails', 'Clubhouse', '24/7 Security', 'Parking Lot', 'Landscaped Gardens'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                ],
            ],
            // ── 9. Bluewaters Island Penthouse ─────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Penthouse',
                'name'           => 'Bluewaters Island Penthouse',
                'location'       => 'Bluewaters Island, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 18000000,
                'size'           => 7400,
                'bedrooms'       => 4,
                'bathrooms'      => 5,
                'parking'        => 3,
                'year_built'     => 2022,
                'description'    => 'An extraordinary penthouse on the exclusive Bluewaters Island, directly adjacent to Ain Dubai — the world\'s largest observation wheel. Four grand bedrooms, a private wraparound terrace, and floor-to-ceiling glazing framing spectacular views of the Arabian Gulf and the illuminated Dubai Marina skyline. An extraordinarily rare opportunity to own on one of Dubai\'s most iconic addresses.',
                'amenities'      => ['Private Terrace', 'Ain Dubai Views', 'Smart Home', 'Swimming Pool', 'Gym', '24/7 Concierge', 'Valet Parking'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                ],
            ],
            // ── 10. Dubai Creek Harbour Waterfront Apartments ──────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Dubai Creek Harbour Waterfront',
                'location'       => 'Dubai Creek Harbour, Dubai',
                'historic_yield' => 9.3,
                'total_assets'   => 7100000,
                'min_investment' => 71000,
                'share_price'    => 710,
                'investors'      => 100,
                'size'           => 1100,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2023,
                'description'    => 'Waterfront 2-bedroom apartments in Emaar\'s ambitious Dubai Creek Harbour development, set to host the future Dubai Creek Tower which will surpass the Burj Khalifa in height. With direct creek and tower views, resort-style amenities, and strong projected capital appreciation, this is one of the most compelling investment locations in the UAE today.',
                'amenities'      => ['Waterfront View', 'Swimming Pool', 'Gym', '24/7 Security', 'Smart Home', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 11. Sobha Hartland Forest Villas ───────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Villa',
                'name'           => 'Sobha Hartland Forest Villas',
                'location'       => 'Sobha Hartland, Mohammed Bin Rashid City, Dubai',
                'historic_yield' => 7.8,
                'total_assets'   => 9200000,
                'min_investment' => 92000,
                'share_price'    => 920,
                'investors'      => 100,
                'size'           => 4200,
                'bedrooms'       => 4,
                'bathrooms'      => 4,
                'parking'        => 3,
                'year_built'     => 2023,
                'description'    => 'Luxurious 4-bedroom forest villas within Sobha Hartland, an 8 million sq ft premium community in Mohammed Bin Rashid City. Surrounded by lush greenery, crystal lagoons, and tree-lined boulevards. Each villa delivers clean lines, premium Italian fixtures, and direct access to the Hartland International School and Sobha Realty\'s award-winning facilities.',
                'amenities'      => ['Crystal Lagoon', 'Private Garden', 'Swimming Pool', 'Smart Home', '24/7 Security', 'Cycling Trails', 'Clubhouse'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1572120360610-d971b9d7767c?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                ],
            ],
            // ── 12. Jumeirah Golf Estates Fairway Mansion ──────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Mansion',
                'name'           => 'Jumeirah Golf Estates Fairway Mansion',
                'location'       => 'Jumeirah Golf Estates, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 22000000,
                'size'           => 12000,
                'bedrooms'       => 6,
                'bathrooms'      => 7,
                'parking'        => 6,
                'year_built'     => 2020,
                'description'    => 'A breathtaking fairway-facing mansion within the world-renowned Jumeirah Golf Estates, host to the DP World Tour Championship. Six expansive en-suite bedrooms, a dedicated home office, private cinema, billiards room, and an outdoor entertainment deck overlooking the championship Earth Course. One of the most prestigious estate addresses in the UAE.',
                'amenities'      => ['Golf Course View', 'Private Pool', 'Home Cinema', 'Smart Home', '24/7 Security', 'Valet Parking', 'Gym'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                ],
            ],
            // ── 13. City Walk Duplex Apartments ────────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Duplex Apartment',
                'name'           => 'City Walk Duplex Residences',
                'location'       => 'City Walk, Al Wasl, Dubai',
                'historic_yield' => 8.2,
                'total_assets'   => 5400000,
                'min_investment' => 54000,
                'share_price'    => 540,
                'investors'      => 100,
                'size'           => 1900,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2021,
                'description'    => 'Designer duplex apartments in the vibrant City Walk open-air district — Dubai\'s most fashionable lifestyle destination with over 300 retail and dining concepts at your doorstep. Double-height living rooms, private terraces, and museum-quality finishes. The community\'s year-round footfall ensures consistently high short-let occupancy rates and outstanding investor returns.',
                'amenities'      => ['Rooftop Pool', 'Smart Home', 'Concierge', '24/7 Security', 'Gym', 'Retail at Doorstep', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 14. Dubai Hills Estate Golf View Villa ─────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Villa',
                'name'           => 'Dubai Hills Golf View Villa',
                'location'       => 'Dubai Hills Estate, Dubai',
                'historic_yield' => 6.9,
                'total_assets'   => 11000000,
                'min_investment' => 110000,
                'share_price'    => 1100,
                'investors'      => 100,
                'size'           => 6200,
                'bedrooms'       => 5,
                'bathrooms'      => 6,
                'parking'        => 4,
                'year_built'     => 2022,
                'description'    => 'An award-winning 5-bedroom villa set on a premium plot within Dubai Hills Estate, Emaar\'s 2,700-acre master community. Overlooking the 18-hole championship Dubai Hills Golf Club, the villa features a sweeping open-plan kitchen and dining area with bi-fold garden doors, a resort-style pool, and premium landscaping. Positioned minutes from Dubai Hills Mall and top international schools.',
                'amenities'      => ['Golf Course View', 'Private Pool', 'Landscaped Garden', 'Smart Home', '24/7 Security', 'Parking Lot', 'Gym'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                ],
            ],
            // ── 15. La Mer Beachfront Apartments ───────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'La Mer Beachfront Residences',
                'location'       => 'La Mer, Jumeirah 1, Dubai',
                'historic_yield' => 9.7,
                'total_assets'   => 4700000,
                'min_investment' => 47000,
                'share_price'    => 470,
                'investors'      => 100,
                'size'           => 850,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'Chic 1-bedroom beachfront apartments in La Mer — Meraas\' beloved Jumeirah coastal lifestyle destination famed for its surf school, beach clubs, and laid-back outdoor dining scene. Each unit delivers direct sea views, generous balconies, and light-filled interiors. A professional short-let operator manages the apartments achieving exceptional 94% occupancy in peak season.',
                'amenities'      => ['Direct Beach Access', 'Swimming Pool', 'Smart Home', '24/7 Security', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
            ],
            // ── 16. Meydan Racecourse District Residences ──────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Meydan District One Apartments',
                'location'       => 'District One, Mohammed Bin Rashid City, Dubai',
                'historic_yield' => 8.6,
                'total_assets'   => 6000000,
                'min_investment' => 60000,
                'share_price'    => 600,
                'investors'      => 100,
                'size'           => 1300,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2023,
                'description'    => 'Contemporary 2-bedroom apartments set directly beside the world\'s largest crystal lagoon within District One in MBR City. Residents enjoy paddleboarding, kayaking, and sandy beach access on a 7 km crystal-clear lagoon just minutes from Downtown Dubai. Managed by a premium hospitality group with full short-let rental services and guaranteed returns in year one.',
                'amenities'      => ['Crystal Lagoon', 'Private Beach', 'Swimming Pool', 'Gym', '24/7 Security', 'Smart Home', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                ],
            ],
            // ── 17. The Palm Tower Sky Suite ───────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Sky Suite',
                'name'           => 'The Palm Tower Sky Suite',
                'location'       => 'The Palm Tower, Palm Jumeirah, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 9800000,
                'size'           => 3200,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2021,
                'description'    => 'A magnificent sky suite within The Palm Tower — the iconic anchor tower of Palm Jumeirah rising next to the five-star St. Regis Dubai. Three opulent bedrooms with panoramic views of the entire Palm, Dubai Marina, and the open Arabian Gulf. Residents have full access to the building\'s infinity pool on the 50th floor, the AURA Skypool Club, and all St. Regis hotel services including in-residence dining.',
                'amenities'      => ['St. Regis Access', 'AURA Skypool', 'Panoramic Views', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Gym'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                ],
            ],
            // ── 18. Tilal Al Ghaf Lagoon Townhouse ─────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Townhouse',
                'name'           => 'Tilal Al Ghaf Lagoon Townhouse',
                'location'       => 'Tilal Al Ghaf, Hessa Street, Dubai',
                'historic_yield' => 7.1,
                'total_assets'   => 4100000,
                'min_investment' => 41000,
                'share_price'    => 410,
                'investors'      => 100,
                'size'           => 3100,
                'bedrooms'       => 4,
                'bathrooms'      => 4,
                'parking'        => 2,
                'year_built'     => 2023,
                'description'    => 'Elegant 4-bedroom townhouses in Majid Al Futtaim\'s highly acclaimed Tilal Al Ghaf community, built around a stunning 70,000 sqm lagoon with a 400-m beach. Thoughtful layouts maximise indoor-outdoor living with private gardens leading to pedestrian-friendly tree-lined greenways. Strong long-let demand from professional families seeking a premium suburban lifestyle within the city.',
                'amenities'      => ['Lagoon Access', 'Private Garden', 'Cycling Trails', 'Swimming Pool', '24/7 Security', 'Parking Lot', 'Clubhouse'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                ],
            ],
            // ── 19. One Za'abeel Dual-Level Residence ──────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Duplex Penthouse',
                'name'           => 'One Za\'abeel Dual-Level Residence',
                'location'       => 'One Za\'abeel, Sheikh Zayed Road, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 35000000,
                'size'           => 9800,
                'bedrooms'       => 5,
                'bathrooms'      => 6,
                'parking'        => 4,
                'year_built'     => 2023,
                'description'    => 'A dual-level super-prime residence within One Za\'abeel, the daring cantilevered twin-tower masterpiece straddling Sheikh Zayed Road. Connected by The Link — the world\'s highest 360° infinity pool — this extraordinary home offers 270° views spanning Burj Khalifa, Dubai Creek, and the Arabian Gulf. Completed to bespoke specification with Italian marble, hand-crafted joinery, and a fully integrated Crestron smart system.',
                'amenities'      => ['World\'s Highest Pool', 'Panoramic Views', 'Smart Home', 'Private Lift', '24/7 Concierge', 'Valet Parking', 'Gym & Spa'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 20. Dubai South Expo Golf Residences ───────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Expo City Golf Residences',
                'location'       => 'Dubai South, Expo City Dubai',
                'historic_yield' => 8.4,
                'total_assets'   => 3200000,
                'min_investment' => 32000,
                'share_price'    => 320,
                'investors'      => 100,
                'size'           => 750,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'Smart 1-bedroom apartments in the rapidly growing Expo City Dubai district — the legacy site of Dubai Expo 2020, now a thriving innovation and business hub adjacent to Al Maktoum International Airport. With Al Maktoum set to become the world\'s largest airport by 2030, the surrounding area commands exceptional long-term capital appreciation alongside competitive current rental yields.',
                'amenities'      => ['Golf Views', 'Swimming Pool', 'Gym', '24/7 Security', 'Smart Home', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
                ],
            ],
            // ── 21. Damac Hills Trump Estates Villa ────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Villa',
                'name'           => 'DAMAC Hills Trump Estate Villa',
                'location'       => 'DAMAC Hills, Dubailand',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 8500000,
                'size'           => 7500,
                'bedrooms'       => 5,
                'bathrooms'      => 6,
                'parking'        => 4,
                'year_built'     => 2020,
                'description'    => 'A magnificent 5-bedroom estate villa on Trump International Golf Club Dubai\'s signature course — one of the world\'s finest 18-hole layouts by Gil Hanse. The villa enjoys a prime fairway-facing plot with sweeping green views, an oversized private pool, shaded terraces, and a fully equipped external summer kitchen. Residents enjoy preferential access to the Trump Golf Club\'s world-class facilities.',
                'amenities'      => ['Trump Golf Access', 'Private Pool', 'Summer Kitchen', 'Smart Home', '24/7 Security', 'Parking Lot', 'Gym'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                ],
            ],
            // ── 22. Al Barari Seventh Heaven Penthouse ─────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Penthouse',
                'name'           => 'Al Barari Seventh Heaven Penthouse',
                'location'       => 'Al Barari, Wadi Al Safa, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 14500000,
                'size'           => 8200,
                'bedrooms'       => 5,
                'bathrooms'      => 6,
                'parking'        => 4,
                'year_built'     => 2019,
                'description'    => 'The crown jewel of Al Barari — Dubai\'s most unique eco-luxury community built across 14 million sq ft of botanic gardens, streams, and nature reserves. This Seventh Heaven penthouse sits atop one of the community\'s signature towers and delivers uninterrupted panoramic views over lush forest canopies. Five grand bedrooms, a private garden terrace with plunge pool, and interiors by a multi-award-winning London design house.',
                'amenities'      => ['Botanical Gardens', 'Plunge Pool', 'Private Terrace', 'Spa', 'Smart Home', '24/7 Security', 'Concierge'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                ],
            ],
            // ── 23. Jumeirah Bay Island Mansion ────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Mansion',
                'name'           => 'Jumeirah Bay Island Waterfront Mansion',
                'location'       => 'Jumeirah Bay Island (Bulgari Resort), Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 85000000,
                'size'           => 22000,
                'bedrooms'       => 7,
                'bathrooms'      => 8,
                'parking'        => 8,
                'year_built'     => 2022,
                'description'    => 'An ultra-prime beachfront mansion on the exclusive seahorse-shaped Jumeirah Bay Island, home to the Bulgari Resort & Residences Dubai — one of the most sought-after luxury addresses on earth. Seven palatial bedrooms, a private two-storey boathouse with 15-metre yacht berth, a 25-metre lap pool, and interiors conceived by Antonio Citterio Patricia Viel. Arguably the most prestigious residential address in the entire Middle East.',
                'amenities'      => ['Private Yacht Berth', 'Bulgari Spa Access', '25m Lap Pool', 'Smart Home', 'Private Beach', '24/7 Concierge', 'Helipad'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                    'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                ],
            ],
            // ── 24. Damac Paramount Tower Hotel Apartment ──────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Hotel Apartment',
                'name'           => 'DAMAC Paramount Tower Hotel Apartment',
                'location'       => 'Business Bay, Dubai',
                'historic_yield' => 9.5,
                'total_assets'   => 3900000,
                'min_investment' => 39000,
                'share_price'    => 390,
                'investors'      => 100,
                'size'           => 700,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2018,
                'description'    => 'Hollywood-glamour branded hotel apartments within DAMAC\'s Paramount Tower in the heart of Business Bay. Operated under the legendary Paramount Hotels & Resorts brand, units are fully furnished to movie-set standards and managed on behalf of owners through a full-service hospitality programme. Investors benefit from a transparent income-share model distributing rental profits monthly.',
                'amenities'      => ['Rooftop Infinity Pool', 'PARAMOUNT Branding', 'Concierge', 'Smart Home', '24/7 Security', 'Gym & Spa', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                ],
            ],
            // ── 25. The Sustainable City Zero-Carbon Villa ─────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Eco Villa',
                'name'           => 'The Sustainable City Zero-Carbon Villa',
                'location'       => 'The Sustainable City, Dubai Production City',
                'historic_yield' => 6.5,
                'total_assets'   => 3500000,
                'min_investment' => 35000,
                'share_price'    => 350,
                'investors'      => 100,
                'size'           => 2600,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2018,
                'description'    => 'A fully zero-carbon villa in Diamond Developers\' internationally acclaimed Sustainable City — the only certified net-zero community in the UAE. Solar-panelled, energy-efficient, surrounded by organic urban farms, equestrian facilities, and green dome biodomes. Service charges are offset by on-site energy generation, delivering one of the lowest total cost of ownership profiles in Dubai real estate.',
                'amenities'      => ['Solar Power', 'Organic Farms', 'Equestrian Centre', 'EV Charging', '24/7 Security', 'Cycling Trails', 'Swimming Pool'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                ],
            ],
            // ── 26. Nakheel Portofino Dubai Harbour Penthouse ──────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Penthouse',
                'name'           => 'Dubai Harbour Portofino Penthouse',
                'location'       => 'Dubai Harbour, Dubai Marina',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 16500000,
                'size'           => 6200,
                'bedrooms'       => 4,
                'bathrooms'      => 5,
                'parking'        => 3,
                'year_built'     => 2023,
                'description'    => 'A spectacular 4-bedroom harbour penthouse at Dubai Harbour — the UAE\'s largest private marina accommodating superyachts up to 160 metres. Overlooking a forest of masts and the azure Arabian Gulf beyond, the wraparound terrace is perfect for outdoor entertaining year-round. Italian-inspired interiors, a sunrise-to-sunset service kitchen, and walk-in wardrobes in every bedroom. Walking distance to the Clinique La Prairie Longevity Centre at Nakheel Marina.',
                'amenities'      => ['Marina Views', 'Private Terrace', 'Swimming Pool', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Spa Access'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                ],
            ],
            // ── 27. Emaar Beachfront Beach Vista Apartments ────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Emaar Beachfront Beach Vista',
                'location'       => 'Emaar Beachfront, Dubai Harbour',
                'historic_yield' => 9.0,
                'total_assets'   => 4800000,
                'min_investment' => 48000,
                'share_price'    => 480,
                'investors'      => 100,
                'size'           => 900,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2023,
                'description'    => 'Bright 1-bedroom sea-view apartments in Emaar Beachfront — a stunning private island community between Dubai Marina and Palm Jumeirah. Residents enjoy exclusive access to a 1.5 km private sandy beach, two resort pools, and an outdoor fitness trail. The development consistently ranks among the most searched Dubai residential projects due to its exceptional lifestyle offering and island connectivity.',
                'amenities'      => ['Private Island Beach', 'Swimming Pool', 'Beach Club', 'Smart Home', '24/7 Security', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 28. Jumeirah Living Marina Gate Serviced Residence ─────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Serviced Residence',
                'name'           => 'Jumeirah Living Marina Gate',
                'location'       => 'Marina Gate, Dubai Marina',
                'historic_yield' => 8.9,
                'total_assets'   => 5200000,
                'min_investment' => 52000,
                'share_price'    => 520,
                'investors'      => 100,
                'size'           => 1050,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2020,
                'description'    => 'Fully serviced 2-bedroom residences managed by Jumeirah Group — one of the world\'s most recognisable luxury hospitality brands — within the prestigious Marina Gate development. Residents receive full five-star hotel services including daily housekeeping, à la carte in-residence dining, a private gym, and a residents-only infinity pool. A dependable income stream asset with blue-chip operator credibility.',
                'amenities'      => ['Jumeirah Hotel Services', 'Infinity Pool', 'Daily Housekeeping', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Spa'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
                ],
            ],
            // ── 29. Creek Views Residences, Al Jaddaf ──────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Al Jaddaf Creek View Apartments',
                'location'       => 'Al Jaddaf Waterfront, Dubai',
                'historic_yield' => 8.1,
                'total_assets'   => 3600000,
                'min_investment' => 36000,
                'share_price'    => 360,
                'investors'      => 100,
                'size'           => 820,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'Stylish 1-bedroom apartments on the tranquil Al Jaddaf waterfront, offering stunning views across Dubai Creek to the historic Deira quarter. Ideally positioned between Downtown Dubai and Dubai International Airport, the development caters to a diverse tenant mix of airline crew, DIFC professionals, and cultural tourists visiting the adjacent Jameel Arts Centre.',
                'amenities'      => ['Creek Views', 'Swimming Pool', 'Gym', '24/7 Security', 'Smart Home', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
            ],
            // ── 30. Mag 318 Smart Micro-Apartments, Downtown ───────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Studio',
                'name'           => 'MAG 318 Downtown Smart Studios',
                'location'       => 'Downtown Dubai, Sheikh Zayed Road',
                'historic_yield' => 11.2,
                'total_assets'   => 1800000,
                'min_investment' => 18000,
                'share_price'    => 180,
                'investors'      => 100,
                'size'           => 380,
                'bedrooms'       => 0,
                'bathrooms'      => 1,
                'parking'        => 0,
                'year_built'     => 2022,
                'description'    => 'Intelligently designed smart studios by MAG Development at the gateway to Downtown Dubai. Every inch optimised through built-in Murphy beds, transformable furniture systems, and fully automated environment controls. Among the highest gross yield assets in the city, commanding over 11% per annum through a short-let management programme targeting business travellers visiting the DIFC and World Trade Centre.',
                'amenities'      => ['Smart Home', 'Co-Working Lounge', 'Swimming Pool', 'Gym', '24/7 Security', 'High-Speed Internet'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 31. Serenia Palm Beach Villa ───────────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Villa',
                'name'           => 'Serenia Palm Beach Villa',
                'location'       => 'Serenia Residences, The Palm, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 27000000,
                'size'           => 9500,
                'bedrooms'       => 6,
                'bathrooms'      => 7,
                'parking'        => 5,
                'year_built'     => 2021,
                'description'    => 'An extraordinary private beach villa at Serenia Residences — one of the Palm\'s most exclusive developments occupying the entire western crescent tip. Set across five floors with a private rooftop pool and sun deck, this villa commands 180° unobstructed views of the open sea and Dubai Marina skyline. Six lavish en-suite bedrooms, a private cinema room, gymnasium, and an elegantly landscaped garden leading directly to a sandy private beach.',
                'amenities'      => ['Private Beach', 'Rooftop Pool', 'Private Cinema', 'Smart Home', '24/7 Security', 'Gym', 'Valet Parking'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                ],
            ],
            // ── 32. Reva Residences Business Bay ───────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'REVA Residences Business Bay',
                'location'       => 'Business Bay, Dubai',
                'historic_yield' => 9.2,
                'total_assets'   => 4400000,
                'min_investment' => 44000,
                'share_price'    => 440,
                'investors'      => 100,
                'size'           => 930,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 1,
                'year_built'     => 2023,
                'description'    => 'Contemporary 2-bedroom apartments in the stylish REVA tower, strategically positioned in Business Bay for both work and lifestyle convenience. Residents enjoy direct canal-walk access, a podium-level infinity pool with Burj Khalifa backdrop, and a sophisticated coworking lounge. High annual rental turnover is sustained by the tower\'s consistent popularity with corporate tenants and digital nomads throughout the year.',
                'amenities'      => ['Canal Walk Access', 'Infinity Pool', 'Co-Working Lounge', 'Smart Home', '24/7 Security', 'Gym', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                ],
            ],
            // ── 33. Kempinski Palm Residence ───────────────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Serviced Apartment',
                'name'           => 'Kempinski Palm Residence',
                'location'       => 'Palm Jumeirah, Dubai',
                'historic_yield' => 8.7,
                'total_assets'   => 6800000,
                'min_investment' => 68000,
                'share_price'    => 680,
                'investors'      => 100,
                'size'           => 1600,
                'bedrooms'       => 2,
                'bathrooms'      => 2,
                'parking'        => 2,
                'year_built'     => 2020,
                'description'    => 'Fully serviced 2-bedroom apartments managed under the iconic Kempinski brand within the Palm Jumeirah\'s signature hotel residence. Owners benefit from a hotel-managed rental scheme while retaining full personal usage rights. Each residence offers a private balcony overlooking the Arabian Gulf, access to Kempinski\'s private beach, and complimentary use of the resort\'s multiple pools and world-class spa.',
                'amenities'      => ['Kempinski Services', 'Private Beach', 'Multi-Pool Complex', 'Spa', '24/7 Concierge', 'Smart Home', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1571939228382-b2f2b585ce15?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 34. Nad Al Sheba Sports City Townhouse ─────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Townhouse',
                'name'           => 'Nad Al Sheba Sports City Townhouse',
                'location'       => 'Nad Al Sheba, Dubai',
                'historic_yield' => 7.4,
                'total_assets'   => 3300000,
                'min_investment' => 33000,
                'share_price'    => 330,
                'investors'      => 100,
                'size'           => 2500,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2024,
                'description'    => 'Off-plan 3-bedroom townhouses in the exciting new Nad Al Sheba Sports City development — a purpose-built community centred on an Olympic-standard track and field complex, aquatic centre, and indoor sports halls. Already attracting strong tenant demand from athletic families and sports professionals. One of the strongest rental yield-to-price ratios available in new Dubai today.',
                'amenities'      => ['Olympic Track', 'Aquatic Centre', 'Private Garden', 'Swimming Pool', '24/7 Security', 'Cycling Trails', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800',
                    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=800',
                ],
            ],
            // ── 35. Bulgari Residences on Jumeirah Bay ─────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Branded Apartment',
                'name'           => 'Bulgari Residences Jumeirah Bay',
                'location'       => 'Jumeirah Bay Island, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 28000000,
                'size'           => 6100,
                'bedrooms'       => 4,
                'bathrooms'      => 5,
                'parking'        => 3,
                'year_built'     => 2022,
                'description'    => 'A supremely rare Bulgari-branded residence on the exclusive Jumeirah Bay Island — one of only 15 apartments in this ultra-private collection. Conceived by Antonio Citterio Patricia Viel with furnishings custom-crafted in Italy, the four-bedroom layout achieves a level of refinement rarely seen in global real estate. Residents enjoy complimentary access to the Bulgari Spa, restaurant, and beach club on one of Dubai\'s most coveted private islands.',
                'amenities'      => ['Bulgari Spa', 'Private Beach', 'Custom Italian Furniture', 'Smart Home', '24/7 Concierge', 'Private Marina Access', 'Valet Parking'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                ],
            ],
            // ── 36. Nakheel Palm Beach Estates Mega Villa ──────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Mega Villa',
                'name'           => 'Palm Beach Estates Mega Villa',
                'location'       => 'Palm Beach Estates, Palm Jumeirah, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 68000000,
                'size'           => 25000,
                'bedrooms'       => 8,
                'bathrooms'      => 10,
                'parking'        => 10,
                'year_built'     => 2024,
                'description'    => 'One of Nakheel\'s most ambitious private residences — an 8-bedroom mega villa at Palm Beach Estates on the iconic Palm Jumeirah. Spanning 25,000 sq ft across four levels, the villa features a double-height grand foyer, home cinema, indoor bowling lane, wine room, and a 30-metre beachfront infinity pool. The rooftop sky lounge commands 360° views across the Gulf, Marina, and Ain Dubai. A truly generational trophy asset.',
                'amenities'      => ['30m Infinity Pool', 'Rooftop Sky Lounge', 'Indoor Bowling', 'Wine Room', 'Home Cinema', 'Private Beach', 'Smart Home', 'Helipad'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800',
                    'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                    'https://images.unsplash.com/photo-1580587771525-78b9dba3b914?w=800',
                ],
            ],
            // ── 37. Atlantis The Royal Residences ──────────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Hotel Residence',
                'name'           => 'Atlantis The Royal Sky Residence',
                'location'       => 'Atlantis The Royal, Palm Jumeirah, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 42000000,
                'size'           => 7800,
                'bedrooms'       => 4,
                'bathrooms'      => 5,
                'parking'        => 3,
                'year_built'     => 2023,
                'description'    => 'Set within Atlantis The Royal — voted the world\'s best new hotel at opening — this sky residence provides exclusive access to 90 world-class experiences including seven pools, 17 restaurants helmed by Michelin-starred chefs, and the Wavehouse waterpark. Interiors by Sou Fujimoto and Missoni Home deliver a completely unique ownership experience that is as much artistic statement as it is real estate investment.',
                'amenities'      => ['17 Michelin-Star Restaurants', 'Seven Pools', 'Waterpark', 'Spa', 'Smart Home', '24/7 Butler', 'Valet Parking'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1512453979798-5ea266f8880c?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1560518883-ce09059eeffa?w=800',
                ],
            ],
            // ── 38. Ellington Belgravia Heights, JVC ───────────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Apartment',
                'name'           => 'Ellington Belgravia Heights JVC',
                'location'       => 'Jumeirah Village Circle (JVC), Dubai',
                'historic_yield' => 8.5,
                'total_assets'   => 2800000,
                'min_investment' => 28000,
                'share_price'    => 280,
                'investors'      => 100,
                'size'           => 700,
                'bedrooms'       => 1,
                'bathrooms'      => 1,
                'parking'        => 1,
                'year_built'     => 2022,
                'description'    => 'Boutique 1-bedroom apartments by Ellington Properties — Dubai\'s most design-conscious developer — within the high-demand Jumeirah Village Circle community. Ellington\'s trademark art-forward lobbies, curated material palettes, and above-category amenity provision create finished homes that consistently outperform the JVC rental market, commanding premium rents from quality-conscious professional tenants.',
                'amenities'      => ['Art Installations', 'Rooftop Pool', 'Gym', '24/7 Security', 'Smart Home', 'High-Speed Internet', 'Parking Lot'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                    'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800',
                ],
            ],
            // ── 39. West Bay Al Habtoor City Penthouse ─────────────────────────
            [
                'listing_type'   => 'for_sale',
                'type'           => 'Penthouse',
                'name'           => 'Al Habtoor City Sky Penthouse',
                'location'       => 'Al Habtoor City, Sheikh Zayed Road, Dubai',
                'historic_yield' => 0,
                'total_assets'   => 0,
                'min_investment' => 0,
                'share_price'    => 0,
                'investors'      => 0,
                'sale_price'     => 19500000,
                'size'           => 7200,
                'bedrooms'       => 4,
                'bathrooms'      => 5,
                'parking'        => 4,
                'year_built'     => 2019,
                'description'    => 'A top-floor sky penthouse in the Noura Tower at Al Habtoor City — a $6 billion mixed-use mega-development on the Dubai Water Canal. The penthouse offers uninterrupted 360° views spanning the Burj Khalifa, Dubai Eye, and the shimmering canal below. Residents have direct access to Cirque du Soleil\'s 1,900-seat theatre, three ultra-luxury hotels, and a remarkable array of wellness and leisure amenities.',
                'amenities'      => ['Canal Views', 'Cirque du Soleil Access', 'Infinity Pool', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Spa'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800',
                    'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800',
                ],
            ],
            // ── 40. Four Seasons Private Residences DIFC ───────────────────────
            [
                'listing_type'   => 'investment',
                'type'           => 'Branded Residence',
                'name'           => 'Four Seasons Private Residences DIFC',
                'location'       => 'Four Seasons Hotel, DIFC, Dubai',
                'historic_yield' => 7.6,
                'total_assets'   => 9500000,
                'min_investment' => 95000,
                'share_price'    => 950,
                'investors'      => 100,
                'size'           => 2200,
                'bedrooms'       => 3,
                'bathrooms'      => 3,
                'parking'        => 2,
                'year_built'     => 2021,
                'description'    => 'Exclusive 3-bedroom branded residences within the Four Seasons Hotel Dubai International Financial Centre — a property synonymous with the finest in global hospitality. Owners receive Four Seasons residential services on demand, including 24-hour in-residence dining, daily housekeeping, and access to the hotel\'s DIFC rooftop pool and Spa. A blue-chip income asset in the heart of the Middle East\'s leading financial district.',
                'amenities'      => ['Four Seasons Services', 'Rooftop Pool', 'Daily Housekeeping', 'Smart Home', '24/7 Concierge', 'Valet Parking', 'Spa'],
                'status'         => 'available',
                'image'          => 'https://images.unsplash.com/photo-1486325212027-8081e485255e?w=800',
                'gallery'        => [
                    'https://images.unsplash.com/photo-1460317442991-0ec209397118?w=800',
                    'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800',
                ],
            ],
        ];

        $total = count($investments);
        foreach ($investments as $i => $inv) {
            $num = $i + 1;

            // Skip if already seeded
            if (Investment::where('name', $inv['name'])->exists()) {
                $this->command->line("[{$num}/{$total}] Skipping (already exists): {$inv['name']}");
                continue;
            }

            $this->command->info("[{$num}/{$total}] Uploading images for: {$inv['name']}");

            // Upload main image
            $mainImage = $this->uploadUrl($inv['image'], 'investments');

            // Upload gallery images
            $galleryUrls = [];
            foreach ($inv['gallery'] as $galleryUrl) {
                $galleryUrls[] = $this->uploadUrl($galleryUrl, 'investments/gallery');
            }

            Investment::create([
                'listing_type'   => $inv['listing_type'],
                'type'           => $inv['type'],
                'name'           => $inv['name'],
                'location'       => $inv['location'],
                'historic_yield' => $inv['historic_yield'],
                'total_assets'   => $inv['total_assets'],
                'sale_price'     => $inv['sale_price'] ?? 0,
                'min_investment' => $inv['min_investment'],
                'share_price'    => $inv['share_price'],
                'investors'      => $inv['investors'],
                'size'           => $inv['size'],
                'bedrooms'       => $inv['bedrooms'],
                'bathrooms'      => $inv['bathrooms'],
                'parking'        => $inv['parking'],
                'year_built'     => $inv['year_built'],
                'description'    => $inv['description'],
                'amenities'      => $inv['amenities'],
                'image'          => $mainImage,
                'gallery'        => $galleryUrls,
                'status'         => $inv['status'],
            ]);

            $this->command->info("  ✓ Done: {$inv['name']}");
        }

        $this->command->info("All {$total} investments seeded successfully!");
    }
}
